In [20]:
import numpy as np
import math
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [17]:
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0 
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop: " + str(1000*(toc-tic)) + "ms")

250159.3131630321
Vectorized version: 0.8609294891357422ms
250159.31316303395
For loop: 191.72382354736328ms


In [35]:
j = 0
dw1 = 0
dw2 = 0
db = 0

for i in range(m):  
    z[i] = np.dot(w, x[i]) + b  
    a[i] = sigmoid(z[i])
    dz[i] = a[i] - y[i]
    dw1 += x1[i] * dz[i]
    dw2 += x2[i] * dz[i]
    db += dz[i]

j /= m
dw1 /= m
dw2 /= m
db /= m


NameError: name 'm' is not defined

In [40]:
m=45
w=98
x=100
y=100
1/m*(np.sum(np.dot(w, x) + b - y))

215566674.14728385

In [43]:
import numpy as np 
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]]) 
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


Axis 0 is up to down
Axis 1 is left to right


In [44]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [50]:
percenta = 100*A/cal
percenta

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [49]:
percentage = 100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [51]:
np.array([[2,1],[1,3]])
a*a

array([1, 4, 9])